services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api
    ports:
      - "80"  # Maps container port 80 (Apache) to localhost:8000
    volumes:
      - .:/var/www
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
